var findpwdApp=angular.module("findpwdApp",[]);
	findpwdApp.controller("findpwdCtrl",function($scope,$http){
		$scope.test="test";
		$scope.isCheckedId=false;
		$scope.findpwd=function(){
			$http({
				url:'findpwd_verifyform.do',
				method:'post',
				params:{user_id:$scope.user_id},
				headers:{"Content-Type":"application/x-www-form-urlencoded;charset=utf-8"}
			}).success(function(data){
				console.log(data)
				if(!data.isExsist){
					alert("존재하지 않는 아이디입니다");
				}else{
					alert("본인인증 페이지로 넘어갑니다");
					$scope.userPhone="01091150444";
					$scope.isCheckedId=true;
				}
			});
		};
		$scope.findpwd_verify=function(){
			$http({
				url:'findpwd_sendSMS.do',
				method:'post',
				params:{userPhone:$scope.userPhone},
				headers:{"Content-Type":"application/x-www-form-urlencoded;charset=utf-8"}
			}).success(function(data){
				alert("인증번호가 전송되었습니다.");
			});
		};
		$scope.findpwd_checkVCode=function(){
			$http({
				url:'findpwd_checkVCode.do',
				method:'post',
				params:{
					userPhone:$scope.userPhone,
					verificationCode:$scope.Vcode
					},
				headers:{"Content-Type":"application/x-www-form-urlencoded;charset=utf-8"}
			}).success(function(data){
				console.log(data);
				if(data.isValid){
					alert("인증되었습니다");
					location.href="changepwd_form.do?userid="+$scope.user_id;
				}
			});
		};
	});